sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=latest
        - EXECUTE_COVERAGE=true
        - EXECUTE_CS_CHECK=true 
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - DEPS=latest
    - php: nightly

  allow_failures:
    - php: nightly

before_install:
  - shopt -s expand_aliases
  - chmod -R +rwX test/asset/data
  - if [[ $EXECUTE_COVERAGE != "true" ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - composer --version
  - php -v
  - php -m

install:
  - if [[ $DEPS == "lowest" ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $DEPS == "latest" ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show --installed

script:
  - if [[ $EXECUTE_COVERAGE == "true" ]] ; then travis_retry vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else travis_retry vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == "true" ]] ; then travis_retry vendor/bin/phpcs ; fi

after_script:
  - if [[ $EXECUTE_COVERAGE == "true" ]] ; then travis_retry php vendor/bin/coveralls ; fi
